version: "3"
services: 
  rabbitmq:
    build: .
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE: ZMRRGAEHZNWKPGKHLPKU
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root